### ISSUE TITLE
Some mistakes need to fix

### ISSUE THREAD

**Issue by JackHCC** [ModestYjx/open-bbs#2]
This period doesn't need
![](https://user-images.githubusercontent.com/39254543/144808392-c17ab434-3a08-4d7c-953f-cda3bdd70747.png)

**Comment by ModestYjx** [comment]
Good brother, good advice, but I look forward to your more participation

**Comment by JACLab-beta** [comment]
Ok, After the final exam, we can do it during the winter vacation

**Comment by ModestYjx** [comment]
Like you bro
